spring:
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: 600000


#spring:
#  application:
#    name: eureka-server
#
## 配置 Eureka Client（可参考 EurekaClientConfigBean）
#eureka:
#  client:
#    service-url:
#      defaultZone: 'http://127.0.0.1:${server.port}/eureka'
