# 首先运行的命令

FROM openjdk:8-jdk-alpine 

From ghcr.io/graalvm/graalvm-ce:latest

VOLUME /tmp 

ARG JAR_FILE 

COPY ${JAR_FILE} app.jar 

# ENTRYPOINT ["java","-jar","/app.jar"]
ENTRYPOINT ["java","-cp","/app.jar", "org.springframework.boot.springbootstarterparent.SpringBootStarterParentApplication"]
